import type { ReviewContext } from '../model/request.js';
import type { CommentRecord } from '../model/comment.js';

export interface RenderOpts {
  partialFiles: string[];
  rawCommentCount?: number;
  filteredCommentCount?: number;
  relocatedCount?: number;
  relocationFallbackCount?: number;
}

/**
 * 渲染 Markdown 报告。模板与 OCR plugins/open-code-review/skills/.../SKILL.md
 * 中给出的"Output Format"段对齐：High Priority / Medium Priority 分组，
 * Low 静默丢弃 (与 OCR 一致)。
 *
 * 本 P0 阶段：评论的 severity 由宿主模型在 content 中自然语言描述，
 * 我们暂时把所有从 jsonl 收集到的 comment 都视为 medium（与 OCR plugin
 * 的"分类与展示由宿主完成"理念一致）；后续 P1 的 REVIEW_FILTER_TASK
 * 可在聚合前对 comment 做 severity 分类。
 */
export function renderMarkdownReport(
  ctx: ReviewContext,
  comments: CommentRecord[],
  opts: RenderOpts,
): string {
  const lines: string[] = [];

  if (opts.partialFiles.length > 0) {
    lines.push('## ⚠️ Warnings', '');
    for (const p of opts.partialFiles) {
      lines.push(`- ${p} 评审未完成 (subagent 未调用 task_done; partial=true)`);
    }
    lines.push('');
  }

  lines.push('## Code Review Results', '');
  lines.push(`**Run**: \`${ctx.runId}\`  `);
  lines.push(`**Range**: \`${ctx.range}\`  `);
  lines.push(`**Files reviewed**: ${ctx.files.length}  `);
  lines.push(`**Issues found**: ${comments.length}`);
  if ((opts.filteredCommentCount ?? 0) > 0) {
    lines.push(`**Filtered**: ${opts.filteredCommentCount} (hidden from raw ${opts.rawCommentCount ?? comments.length})  `);
  }
  const relocCount = opts.relocatedCount ?? 0;
  const fbCount = opts.relocationFallbackCount ?? 0;
  if (relocCount > 0 || fbCount > 0) {
    lines.push(`**Relocated**: ${relocCount} (fallback ${fbCount})  `);
  }
  lines.push('');

  if (comments.length === 0) {
    lines.push(`Review complete — no issues found in ${ctx.files.length} file(s).`);
    return lines.join('\n');
  }

  // 按文件 + 起始行排序
  const sorted = [...comments].sort((a, b) => {
    if (a.path !== b.path) return a.path < b.path ? -1 : 1;
    return a.start_line - b.start_line;
  });

  lines.push('### Comments', '');
  for (const c of sorted) {
    const range =
      c.start_line === c.end_line ? `${c.start_line}` : `${c.start_line}-${c.end_line}`;
    lines.push(`- **\`${c.path}:${range}\`** — ${c.content.split('\n')[0]}`);
    if (c.content.includes('\n')) {
      const rest = c.content.split('\n').slice(1).join('\n');
      lines.push('  ', '  ' + rest.split('\n').join('\n  '));
    }
    if (c.suggestion_code) {
      lines.push('', '  Suggested:', '', '  ```', '  ' + c.suggestion_code.split('\n').join('\n  '), '  ```');
    }
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`_Generated by open-code-review-plugin ${ctx.meta.pluginVersion} at ${ctx.meta.generatedAt}_`);
  return lines.join('\n');
}
